# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c115e319968b2b104e0448415ddc446ff4a9f1197a621a4f40f5b6e2c8b772dad88475397a7292baba9eeaf7dcc31b1d0c7d8c55ba261156f0c4470d1c1e7c

test:
  secret_key_base: 72b402db7d188016e18e983a7d24aee174e59131942474140582dab24793180d9ab2f20759e5e2ec8ab84b07e32f5e89c5b085ecff242abf5b8b94826c9a7ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
